### ISSUE TITLE
[BUG] [Backup Download] InvalidRequestThe authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.[...]

### ISSUE THREAD

**Issue by EugeneLeclerc** [VeriorPies/MineCloud#47]
Hi! Thanks for the project, it seems interesting.

I just installed MineCloud and it went well. I started it, connected to it, played for a few minutes and then started a backup. 

Then I tried to ask for the download link. I'm unfamiliar with S3, so I wont paste the whole answer here in case it contains sensitive information, but it was a long-ass link. When I clicked on it, I got the following error:

> InvalidRequestThe authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.[...]

(the [...] is again a chain of character I'm not putting here, don't know if it's security sensitive)

I googled the error, it seems to be a problem with my region, which is `eu-west-3`. Looks like US regions support an older authorization mechanism that is not supported in Europe: [Stack Overlow exemple](https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4)

Again thanks a lot ;)

**Comment by 314pies** [comment]
Hi [EugeneLeclerc](https://github.com/EugeneLeclerc),  
Thanks for reporting this issue. I will take a look!

**Comment by 314pies** [comment]
Hi [EugeneLeclerc](https://github.com/EugeneLeclerc),
This issue now should be fixed in the 1.2.1 release:  
https://github.com/VeriorPies/MineCloud/releases/tag/1.2.1

Let me know if you are still having this issue!
