### ISSUE TITLE
[Feature request] Update a Route53 DNS record with the IP of the EC2 instance

### ISSUE THREAD

**Issue by mrumpf** [VeriorPies/MineCloud#68]
**Is your feature request related to a problem? Please describe.**
Every time the Ec2 machine starts, a script could be run to update a configurable DNS record.

**Describe the solution you'd like**
I own a domain which I would like to use to make it easier to connect to the server by creating a record like minecraft.mydomain.cloud.

In the guide [How to automatically update IP addresses](https://dev.to/aws/amazon-route-53-how-to-automatically-update-ip-addresses-without-using-elastic-ips-h7o) a script is run at each boot to update a DNS record with the new IP address. The DNS name is added as a tag to the EC2 instance.
This could also be implemented as a [Linux systemd service](https://stackoverflow.com/a/73779270/1518964)

An alternative solution would be to integrate the DNS update functionality into the Lambda function which posts the IP address into the Discord channel.

Whatever solution is implemented, the script could look at the EC2 instance tags and if there is a DNS_RECORD tag present it could execute the update Route53 dns record functionality. This would make this an optional feature, which can be controlled by giving an optional environment variable DNS_RECORD_TAG=minecraft.mydomain.cloud

**Comment by mrumpf** [comment]
BTW, the script in the linked guide shows a way how to get the public IP from inside the machine, without having to consult an external service like opendns.

**Comment by 314pies** [comment]
Cool, I like this idea!  

If any also interested in this feature, please leave a comment or reaction so we know you need it!
